In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# Linear Algebra

In [2]:
x = np.array([4,2])
y = np.array([1,4])
x @ y

12

### Matrices

In [3]:
X = np.array([[1,2],[1,4],[np.exp(1),4]])

In [4]:
X.T @ X

array([[ 9.3890561 , 16.87312731],
       [16.87312731, 36.        ]])

In [5]:
X = np.array([[1,4,5],[10,2,3]])
Y = np.array([[2,3],[1,5],[3,5]])
X @ Y

array([[21, 48],
       [31, 55]])

In [6]:
X = np.array([[2,3,4],[3,1,3], [2,4,2]])
X_inv = np.linalg.inv(X)
X @ X_inv

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [7]:
A = np.array([[3],[-2],[9]])
B = np.array([[8],[0],[-1]])
C = np.array([[7, -1, 5],[0,2,-4]])
D = np.array([[3,1],[3,4],[3,-7]])
E = np.array([[5,2,3],[1,0,-4],[-2,1,-6]])
F = np.array([[4,1,-5],[0,7,7],[2,-3,0]])
G = np.array([[2,-8,-5],[-3,7,-4],[1,0,3],[1,2,6]])
K = np.array([[9],[-2],[-1],[0]])
L = np.array([[5,0,3,1]])

In [8]:
A + B

array([[11],
       [-2],
       [ 8]])

In [9]:
-G

array([[-2,  8,  5],
       [ 3, -7,  4],
       [-1,  0, -3],
       [-1, -2, -6]])

In [10]:
D.T

array([[ 3,  3,  3],
       [ 1,  4, -7]])

In [11]:
# C + D # conformability error

In [12]:
3*C - 2*D.T

array([[15, -9,  9],
       [-2, -2,  2]])

In [13]:
np.inner(A.T,B.T)

array([[15]])

In [14]:
C @ B

array([[51],
       [ 4]])

In [15]:
# B @ C

In [16]:
F @ B

array([[37],
       [-7],
       [16]])

In [17]:
E @ F

array([[ 26,  10, -11],
       [ -4,  13,  -5],
       [-20,  23,  17]])

In [18]:
np.inner(K.T, L)

array([[42]])

In [19]:
np.linalg.norm(K)

9.273618495495704

In [20]:
G.T

array([[ 2, -3,  1,  1],
       [-8,  7,  0,  2],
       [-5, -4,  3,  6]])

In [21]:
E - 5*np.eye(3)

array([[  0.,   2.,   3.],
       [  1.,  -5.,  -4.],
       [ -2.,   1., -11.]])

In [22]:
Q = np.array([[1,3],[2,7]])
np.linalg.inv(Q)

array([[ 7., -3.],
       [-2.,  1.]])

In [23]:
G

array([[ 2, -8, -5],
       [-3,  7, -4],
       [ 1,  0,  3],
       [ 1,  2,  6]])

In [24]:
F = np.array([[4,1,-5],[0,7,7],[2,-3,0]])
G = np.array([[4,1,-5],[2,-3,0],[0,7,7]])

In [25]:
np.linalg.det(F)
np.linalg.det(G)

167.99999999999997

-167.99999999999997

In [26]:
A = np.array([[1,9,6],[3,10,-1],[8,38,10]])
B = np.array([[8,-2,4,10],[0,0,1,-1],[-9,8,0,0],[1,0,0,0]])
C = np.array([[0,1],[0,0]])

In [27]:
# np.linalg.inv(A)

In [28]:
np.linalg.inv(B)

array([[ 1.93082265e-17, -7.72329061e-17, -0.00000000e+00,
         1.00000000e+00],
       [ 2.17217548e-17, -8.68870193e-17,  1.25000000e-01,
         1.12500000e+00],
       [ 7.14285714e-02,  7.14285714e-01,  1.78571429e-02,
        -4.10714286e-01],
       [ 7.14285714e-02, -2.85714286e-01,  1.78571429e-02,
        -4.10714286e-01]])

In [29]:
# np.linalg.inv(C)